export const TOKENS_NOT_FOUND = "TOKENS_NOT_FOUND";
export const TOKEN_ACCESS_NOT_VALID = "TOKEN_ACCESS_NOT_VALID";
export const TOKEN_REFRESH_NOT_VALID = "TOKEN_REFRESH_NOT_VALID";
export const TOKEN_REFRESH_IS_BLACKLISTED = "TOKEN_REFRESH_IS_BLACKLISTED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_NOT_VERIFICATED = "USER_NOT_VERIFICATED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const GETUSER_SUCCESS = "GETUSER_SUCCESS";
export const GETUSER_FAIL = "GETUSER_FAIL";
export const GETUSER_FAIL_REFRESH = "GETUSER_FAIL_REFRESH";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAIL = "REFRESH_FAIL";
export const SET_LOGOUT_FALSE = "SET_LOGOUT_FALSE";
export const CLEAR_PASSWORD_RESET = "CLEAR_PASSWORD_RESET";
export const ACCOUNT_CONFIRM_SUCCESS = "ACCOUNT_CONFIRM_SUCCESS";
export const ACCOUNT_CONFIRM_FAIL = "ACCOUNT_CONFIRM_FAIL";
export const GENERATE_NEWCODE_SUCCESS = "GENERATE_NEWCODE_SUCCESS";
export const GENERATE_NEWCODE_FAIL = "GENERATE_NEWCODE_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const DATA_HOMESCREEN_SUCCESS = "DATA_HOMESCREEN_SUCCESS";
export const DATA_HOMESCREEN_FAIL = "DATA_HOMESCREEN_FAIL";
export const DATA_HOMESCREEN_NEXT_SUCCESS = "DATA_HOMESCREEN_NEXT_SUCCESS";
export const DATA_HOMESCREEN_NEXT_FAIL = "DATA_HOMESCREEN_NEXT_FAIL";
export const CATEGORY_HOMESCREEN_SUCCESS = "CATEGORY_HOMESCREEN_SUCCESS";
export const CATEGORY_HOMESCREEN_FAIL = "CATEGORY_HOMESCREEN_FAIL";
export const DATA_PROVINCE_SUCCESS = "DATA_PROVINCE_SUCCESS";
export const DATA_PROVINCE_FAIL = "DATA_PROVINCE_FAIL";
export const DATA_CITIES_SUCCESS = "DATA_CITIES_SUCCESS";
export const DATA_CITIES_FAIL = "DATA_CITIES_FAIL";
export const CHANGE_USER_LOCATION_SUCCESS = "CHANGE_USER_LOCATION_SUCCESS";
export const CHANGE_USER_LOCATION_FAIL = "CHANGE_USER_LOCATION_FAIL";
export const CHANGE_USER_DISTANCE_SUCCESS = "CHANGE_USER_DISTANCE_SUCCESS";
export const CHANGE_USER_DISTANCE_FAIL = "CHANGE_USER_DISTANCE_FAIL";
export const CHECK_LOCALIZATION_SUCCESS = "CHECK_LOCALIZATION_SUCCESS";
export const CHECK_LOCALIZATION_FAIL = "CHECK_LOCALIZATION_FAIL";
export const EVENT_LIST_SUCCESS = "EVENT_LIST_SUCCESS";
export const EVENT_LIST_FAIL = "EVENT_LIST_FAIL";
export const EVENT_SUCCESS = "EVENT_SUCCESS";
export const EVENT_FAIL = "EVENT_FAIL";
export const CLEAR_CITIES = "CLEAR_CITIES";
export const MENU_STATE_CHANGE = "MENU_STATE_CHANGE";
export const COMMENT_EVENT_SUCCESS = "COMMENT_EVENT_SUCCESS";
export const COMMENT_EVENT_FAIL = "COMMENT_EVENT_FAIL";
export const COMMENT_EVENT_REACTION_SUCCESS = "COMMENT_EVENT_REACTION_SUCCESS";
export const COMMENT_EVENT_REACTION_FAIL = "COMMENT_EVENT_REACTION_FAIL";
export const COMMENT_EVENT_REPORT_SUCCESS = "COMMENT_EVENT_REPORT_SUCCESS";
export const COMMENT_EVENT_REPORT_FAIL = "COMMENT_EVENT_REPORT_FAIL";
export const COMMENT_EVENT_NOTVALID = "COMMENT_EVENT_NOTVALID";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";
export const CLEAR_EVENT = "CLEAR_EVENT";
export const COMMENT_EVENT_POST_SUCCESS = "COMMENT_EVENT_POST_SUCCESS";
export const COMMENT_EVENT_POST_FAIL = "COMMENT_EVENT_POST_FAIL";
export const COMMENT_EVENT_DELETE_SUCCESS = "COMMENT_EVENT_DELETE_SUCCESS";
export const COMMENT_EVENT_DELETE_FAIL = "COMMENT_EVENT_DELETE_FAIL";
export const EVENT_USER_SUCCESS = "EVENT_USER_SUCCESS";
export const EVENT_USER_FAIL = "EVENT_USER_FAIL";
export const EVENT_USER_PARTICIPATE_SUCCESS = "EVENT_USER_PARTICIPATE_SUCCESS";
export const EVENT_USER_PARTICIPATE_FAIL = "EVENT_USER_PARTICIPATE_FAIL";
export const EVENT_PARTICIPANTS_SUCCESS = "EVENT_PARTICIPANTS_SUCCESS";
export const EVENT_PARTICIPANTS_FAIL = "EVENT_PARTICIPANTS_FAIL";
export const FRIEND_REQUEST_SUCCESS = "FRIEND_REQUEST_SUCCESS";
export const FRIEND_REQUEST_NOTVALID_SUCCESS =
  "FRIEND_REQUEST_NOTVALID_SUCCESS";
export const FRIEND_REQUEST_FAIL = "FRIEND_REQUEST_FAIL";
export const WEBSOCKETS_FRIEND_REQUEST_REACTION_SUCCESS =
  "WEBSOCKETS_FRIEND_REQUEST_REACTION_SUCCESS";
export const FRIEND_REQUEST_REACTION_NOTVALID_SUCCESS =
  "FRIEND_REQUEST_REACTION_NOTVALID_SUCCESS";
export const FRIEND_REQUEST_REACTION_FAIL = "FRIEND_REQUEST_REACTION_FAIL";
export const FRIEND_REMOVE_SUCCESS = "FRIEND_REMOVE_SUCCESS";
export const FRIEND_REMOVE_NOTVALID_SUCCESS = "FRIEND_REMOVE_NOTVALID_SUCCESS";
export const FRIEND_REMOVE_FAIL = "FRIEND_REMOVE_FAIL";
export const EVENT_CREATE_SUCCESS = "EVENT_CREATE_SUCCESS";
export const EVENT_CREATE_FAIL = "EVENT_CREATE_FAIL";
export const SERIES_SUCCESS = "SERIES_SUCCESS";
export const SERIES_FAIL = "SERIES_FAIL";
export const EVENT_REPORT_SUCCESS = "EVENT_REPORT_SUCCESS";
export const EVENT_REPORT_FAIL = "EVENT_REPORT_FAIL";
export const EVENT_DELETE_SUCCESS = "EVENT_DELETE_SUCCESS";
export const EVENT_DELETE_FAIL = "EVENT_DELETE_FAIL";
export const EVENT_EDIT_SUCCESS = "EVENT_EDIT_SUCCESS";
export const EVENT_EDIT_FAIL = "EVENT_EDIT_FAIL";
export const EVENT_VIA_SERIES_SUCCESS = "EVENT_VIA_SERIES_SUCCESS";
export const EVENT_VIA_SERIES_FAIL = "EVENT_VIA_SERIES_FAIL";
export const EVENT_ADD_SERIES_SUCCESS = "EVENT_ADD_SERIES_SUCCESS";
export const EVENT_ADD_SERIES_FAIL = "EVENT_ADD_SERIES_FAIL";
export const EVENT_DELETE_SERIES_SUCCESS = "EVENT_DELETE_SERIES_SUCCESS";
export const EVENT_DELETE_SERIES_FAIL = "EVENT_DELETE_SERIES_FAIL";
export const SERIES_CREATE_SUCCESS = "SERIES_CREATE_SUCCESS";
export const SERIES_CREATE_FAIL = "SERIES_CREATE_FAIL";
export const SERIES_DELETE_SUCCESS = "SERIES_DELETE_SUCCESS";
export const SERIES_DELETE_FAIL = "SERIES_DELETE_FAIL";
export const SERIES_EDIT_SUCCESS = "SERIES_EDIT_SUCCESS";
export const SERIES_EDIT_FAIL = "SERIES_EDIT_FAIL";
export const EVENT_VIA_CALENDAR_SUCCESS = "EVENT_VIA_CALENDAR_SUCCESS";
export const EVENT_VIA_CALENDAR_FAIL = "EVENT_VIA_CALENDAR_FAIL";
export const EVENT_RANDOM_SUCCESS = "EVENT_RANDOM_SUCCESS";
export const EVENT_RANDOM_FAIL = "EVENT_RANDOM_FAIL";
export const EVENT_RANDOM_REACTION_SUCCESS = "EVENT_RANDOM_REACTION_SUCCESS";
export const EVENT_RANDOM_REACTION_FAIL = "EVENT_RANDOM_REACTION_FAIL";
export const CLEAR_EVENT_RANDOM = "CLEAR_EVENT_RANDOM";
export const EVENT_PROVINCE_MAP_SUCCESS = "EVENT_PROVINCE_MAP_SUCCESS";
export const EVENT_PROVINCE_MAP_FAIL = "EVENT_PROVINCE_MAP_FAIL";
export const EVENT_COUNTY_MAP_SUCCESS = "EVENT_COUNTY_MAP_SUCCESS";
export const EVENT_COUNTY_MAP_FAIL = "EVENT_COUNTY_MAP_FAIL";
export const FIND_FRIENDS_SUCCESS = "FIND_FRIENDS_SUCCESS";
export const FIND_FRIENDS_FAIL = "FIND_FRIENDS_FAIL";
export const FIND_FRIENDS_NEXT_SUCCESS = "FIND_FRIENDS_NEXT_SUCCESS";
export const FIND_FRIENDS_NEXT_FAIL = "FIND_FRIENDS_NEXT_FAIL";
export const EVENT_VIA_BAGDES_SUCCESS = "EVENT_VIA_BAGDES_SUCCESS";
export const EVENT_VIA_BAGDES_FAIL = "EVENT_VIA_BAGDES_FAIL";
export const BADGECODES_LOCKED_SUCCESS = "BADGECODES_LOCKED_SUCCESS";
export const BADGECODES_LOCKED_FAIL = "BADGECODES_LOCKED_FAIL";
export const BADGECODES_CREATE_SUCCESS = "BADGECODES_CREATE_SUCCESS";
export const BADGECODES_CREATE_FAIL = "BADGECODES_CREATE_FAIL";
export const BADGECODES_DELETE_SUCCESS = "BADGECODES_DELETE_SUCCESS";
export const BADGECODES_DELETE_FAIL = "BADGECODES_DELETE_FAIL";
export const BADGE_EDIT_SUCCESS = "BADGE_EDIT_SUCCESS";
export const BADGE_EDIT_FAIL = "BADGE_EDIT_FAIL";
export const BADGE_CREATE_SUCCESS = "BADGE_CREATE_SUCCESS";
export const BADGE_CREATE_FAIL = "BADGE_CREATE_FAIL";
export const BADGE_DELETE_SUCCESS = "BADGE_DELETE_SUCCESS";
export const BADGE_DELETE_FAIL = "BADGE_DELETE_FAIL";
export const USER_BADGES_SUCCESS = "USER_BADGES_SUCCESS";
export const USER_BADGES_FAIL = "USER_BADGES_FAIL";
export const BADGE_ACTIVATE_SUCCESS = "BADGE_ACTIVATE_SUCCESS";
export const BADGE_ACTIVATE_NOTVALID_CODE_SUCCESS =
  "BADGE_ACTIVATE_NOTVALID_CODE_SUCCESS";
export const BADGE_ACTIVATE_FAIL = "BADGE_ACTIVATE_FAIL";
export const BADGE_REPORT_SUCCESS = "BADGE_REPORT_SUCCESS";
export const BADGE_REPORT_FAIL = "BADGE_REPORT_FAIL";
export const USER_VALIDATORS_SUCCESS = "USER_VALIDATORS_SUCCESS";
export const USER_VALIDATORS_FAIL = "USER_VALIDATORS_FAIL";
export const USER_BLOCKED_USERS_SUCCESS = "USER_BLOCKED_USERS_SUCCESS";
export const USER_BLOCKED_USERS_FAIL = "USER_BLOCKED_USERS_FAIL";
export const LOGOUT_FROM_DEVICES_SUCCESS = "LOGOUT_FROM_DEVICES_SUCCESS";
export const LOGOUT_FROM_DEVICES_NOTVALID_SUCCESS =
  "LOGOUT_FROM_DEVICES_NOTVALID_SUCCESS";
export const LOGOUT_FROM_DEVICES_FAIL = "LOGOUT_FROM_DEVICES_FAIL";
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_FAIL = "BLOCK_USER_FAIL";
export const UNBLOCK_USER_SUCCESS = "UNBLOCK_USER_SUCCESS";
export const UNBLOCK_USER_NOTVALID_SUCCESS = "UNBLOCK_USER_NOTVALID_SUCCESS";
export const UNBLOCK_USER_FAIL = "UNBLOCK_USER_FAIL";
export const UNLINKED_GOOGLE_SUCCESS = "UNLINKED_GOOGLE_SUCCESS";
export const UNLINKED_GOOGLE_FAIL = "UNLINKED_GOOGLE_FAIL";
export const UNLINKED_FACEBOOK_SUCCESS = "UNLINKED_FACEBOOK_SUCCESS";
export const UNLINKED_FACEBOOK_FAIL = "UNLINKED_FACEBOOK_FAIL";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAIL = "PASSWORD_CHANGE_FAIL";
export const PASSWORD_CHANGE_CONFIRM_SUCCESS =
  "PASSWORD_CHANGE_CONFIRM_SUCCESS";
export const PASSWORD_CHANGE_CONFIRM_FAIL = "PASSWORD_CHANGE_CONFIRM_FAIL";
export const EMAIL_CHANGE_SUCCESS = "EMAIL_CHANGE_SUCCESS";
export const EMAIL_CHANGE_FAIL = "EMAIL_CHANGE_FAIL";
export const EMAIL_CHANGE_CONFIRM_SUCCESS = "EMAIL_CHANGE_CONFIRM_SUCCESS";
export const EMAIL_CHANGE_CONFIRM_NOTVALID_SUCCESS =
  "EMAIL_CHANGE_CONFIRM_NOTVALID_SUCCESS";
export const EMAIL_CHANGE_CONFIRM_FAIL = "EMAIL_CHANGE_CONFIRM_FAIL";
export const SET_NEW_EMAIL = "SET_NEW_EMAIL";
export const GENERATE_NEWCODE_EMAIL_SUCCESS = "GENERATE_NEWCODE_EMAIL_SUCCESS";
export const GENERATE_NEWCODE_EMAIL_NOTVALID_SUCCESS =
  "GENERATE_NEWCODE_EMAIL_NOTVALID_SUCCESS";
export const GENERATE_NEWCODE_EMAIL_FAIL = "GENERATE_NEWCODE_EMAIL_FAIL";
export const ACCOUNT_DELETE_SUCCESS = "ACCOUNT_DELETE_SUCCESS";
export const ACCOUNT_DELETE_FAIL = "ACCOUNT_DELETE_FAIL";
export const ACCOUNT_EDIT_SUCCESS = "ACCOUNT_EDIT_SUCCESS";
export const ACCOUNT_EDIT_FAIL = "ACCOUNT_EDIT_FAIL";
export const BADGE_SETTINGS_SUCCESS = "BADGE_SETTINGS_SUCCESS";
export const BADGE_SETTINGS_FAIL = "BADGE_SETTINGS_FAIL";
export const BADGE_SET_MAIN_SUCCESS = "BADGE_SET_MAIN_SUCCESS";
export const BADGE_SET_MAIN_NOTVALID_SUCCESS =
  "BADGE_SET_MAIN_NOTVALID_SUCCESS";
export const BADGE_SET_MAIN_FAIL = "BADGE_SET_MAIN_FAIL";
export const EVENT_IS_DELETED = "EVENT_IS_DELETED";
export const EVENT_IS_REJECTED = "EVENT_IS_REJECTED";
export const ADMIN_LOGS_SUCCESS = "ADMIN_LOGS_SUCCESS";
export const ADMIN_LOGS_FAIL = "ADMIN_LOGS_FAIL";
export const ADMIN_LOGS_NEXT_SUCCESS = "ADMIN_LOGS_NEXT_SUCCESS";
export const ADMIN_LOGS_NEXT_FAIL = "ADMIN_LOGS_NEXT_FAIL";
export const ADMIN_LOGS_REFRESH_SUCCESS = "ADMIN_LOGS_REFRESH_SUCCESS";
export const ADMIN_LOGS_REFRESH_FAIL = "ADMIN_LOGS_REFRESH_FAIL";
export const ADMIN_RESET = "ADMIN_RESET";
export const DATA_RESET = "DATA_RESET";
export const EVENT_IS_NOT_VERIFICATED = "EVENT_IS_NOT_VERIFICATED";
export const BADGE_IS_NOT_VERIFICATED = "BADGE_IS_NOT_VERIFICATED";
export const BADGE_IS_DELETED = "BADGE_IS_DELETED";
export const BADGE_OWNER_IS_DELETED = "BADGE_OWNER_IS_DELETED";
export const BADGE_OWNER_IS_NOT_VERIFICATED = "BADGE_OWNER_IS_NOT_VERIFICATED";
export const ADMIN_DATA_SUCCESS = "ADMIN_DATA_SUCCESS";
export const ADMIN_DATA_FAIL = "ADMIN_DATA_FAIL";
export const ADMIN_DATA_NEXT_SUCCESS = "ADMIN_DATA_NEXT_SUCCESS";
export const ADMIN_DATA_NEXT_FAIL = "ADMIN_DATA_NEXT_FAIL";
export const ADMIN_DATA_ACTION_SUCCESS = "ADMIN_DATA_ACTION_SUCCESS";
export const ADMIN_DATA_ACTION_NOTVALID_SUCCESS =
  "ADMIN_DATA_ACTION_NOTVALID_SUCCESS";
export const ADMIN_DATA_ACTION_USERCHANGED_SUCCESS =
  "ADMIN_DATA_ACTION_USERCHANGED_SUCCESS";
export const ADMIN_DATA_ACTION_FAIL = "ADMIN_DATA_ACTION_FAIL";
export const IPADDRESS_BANNED = "IPADDRESS_BANNED";
export const USER_BANNED = "USER_BANNED";
export const USER_DELETED = "USER_DELETED";
export const IPADDRESS_DELETED = "IPADDRESS_DELETED";
export const ADMIN_NOT_PERMISSION = "ADMIN_NOT_PERMISSION";
export const ADMIN_DATA_LOGOUT_NOTVALID_SUCCESS =
  "ADMIN_DATA_LOGOUT_NOTVALID_SUCCESS";
export const WEBSOCKETS_CONNECT_SUCCESS = "WEBSOCKETS_CONNECT_SUCCESS";
export const WEBSOCKETS_CONNECT_FAIL = "WEBSOCKETS_CONNECT_FAIL";
export const WEBSOCKETS_DISCONNECTED = "WEBSOCKETS_DISCONNECTED";
export const WEBSOCKETS_CONTACT_STATE_CHANGE =
  "WEBSOCKETS_CONTACT_STATE_CHANGE";
export const WEBSOCKETS_FRIENDS_LIST_SUCCESS =
  "WEBSOCKETS_FRIENDS_LIST_SUCCESS";
export const WEBSOCKETS_FRIENDS_LIST_FAIL = "WEBSOCKETS_FRIENDS_LIST_FAIL";
export const WEBSOCKETS_FRIENDS_LIST_NEXT_SUCCESS =
  "WEBSOCKETS_FRIENDS_LIST_NEXT_SUCCESS";
export const WEBSOCKETS_FRIENDS_LIST_NEXT_FAIL =
  "WEBSOCKETS_FRIENDS_LIST_NEXT_FAIL";
export const WEBSOCKETS_MESSAGES_LIST_SUCCESS =
  "WEBSOCKETS_MESSAGES_LIST_SUCCESS";
export const WEBSOCKETS_MESSAGES_LIST_FAIL = "WEBSOCKETS_MESSAGES_LIST_FAIL";
export const WEBSOCKETS_MESSAGES_LIST_NEXT_SUCCESS =
  "WEBSOCKETS_MESSAGES_LIST_NEXT_SUCCESS";
export const WEBSOCKETS_MESSAGES_LIST_NEXT_FAIL =
  "WEBSOCKETS_MESSAGES_LIST_NEXT_FAIL";
export const WEBSOCKETS_CHAT_OPEN = "WEBSOCKETS_CHAT_OPEN";
export const WEBSOCKETS_CHAT_CLOSE = "WEBSOCKETS_CHAT_CLOSE";
export const WEBSOCKETS_CONVERSATION_SUCCESS =
  "WEBSOCKETS_CONVERSATION_SUCCESS";
export const WEBSOCKETS_CONVERSATION_FAIL = "WEBSOCKETS_CONVERSATION_FAIL";
export const WEBSOCKETS_SEND_MESSAGE_SUCCESS =
  "WEBSOCKETS_SEND_MESSAGE_SUCCESS";
export const WEBSOCKETS_SEND_MESSAGE_FAIL = "WEBSOCKETS_SEND_MESSAGE_FAIL";
export const WEBSOCKETS_SENDING_MESSAGE_SUCCESS =
  "WEBSOCKETS_SENDING_MESSAGE_SUCCESS";
export const WEBSOCKETS_SENDING_MESSAGE_FAIL =
  "WEBSOCKETS_SENDING_MESSAGE_FAIL";
export const WEBSOCKETS_RECEIVE_MESSAGE_SUCCESS =
  "WEBSOCKETS_RECEIVE_MESSAGE_SUCCESS";
export const WEBSOCKETS_RECEIVE_MESSAGE_FAIL =
  "WEBSOCKETS_RECEIVE_MESSAGE_FAIL";
export const WEBSOCKETS_MESSAGES_DELIVERED = "WEBSOCKETS_MESSAGES_DELIVERED";
export const WEBSOCKETS_ONLINE_FRIENDS_SUCCESS =
  "WEBSOCKETS_ONLINE_FRIENDS_SUCCESS";
export const WEBSOCKETS_ONLINE_FRIENDS_FAIL = "WEBSOCKETS_ONLINE_FRIENDS_FAIL";
export const WEBSOCKETS_CLEAR_COOKIES_SUCCESS =
  "WEBSOCKETS_CLEAR_COOKIES_SUCCESS";
export const WEBSOCKETS_CLEAR_COOKIES_FAIL = "WEBSOCKETS_CLEAR_COOKIES_FAIL";
export const WEBSOCKETS_FILTER_REMOVE_FRIEND_LIST =
  "WEBSOCKETS_FILTER_REMOVE_FRIEND_LIST";
export const WEBSOCKETS_FILTER_ADD_FRIEND_LIST =
  "WEBSOCKETS_FILTER_ADD_FRIEND_LIST";
export const WEBSOCKETS_CLEAR_REDUCER = "WEBSOCKETS_CLEAR_REDUCER";
export const WEBSOCKETS_CATCH_BLOCKED_STATUS =
  "WEBSOCKETS_CATCH_BLOCKED_STATUS";
export const WEBSOCKETS_CATCH_UNBLOCKED_STATUS =
  "WEBSOCKETS_CATCH_UNBLOCKED_STATUS";
export const WEBSOCKETS_CATCH_DELETED_USER = "WEBSOCKETS_CATCH_DELETED_USER";
export const WEBSOCKETS_INVITATIONS_LIST_NEXT_SUCCESS =
  "WEBSOCKETS_INVITATIONS_LIST_NEXT_SUCCESS";
export const WEBSOCKETS_INVITATIONS_LIST_NEXT_FAIL =
  "WEBSOCKETS_INVITATIONS_LIST_NEXT_FAIL";
export const WEBSOCKETS_INVITATIONS_STATE_CHANGE =
  "WEBSOCKETS_INVITATIONS_STATE_CHANGE";
export const WEBSOCKETS_INVITATION_REMOVE = "WEBSOCKETS_INVITATION_REMOVE";
export const WEBSOCKETS_SEND_INVITE_FAIL = "WEBSOCKETS_SEND_INVITE_FAIL";
export const WEBSOCKETS_GET_INVITE_SUCCESS = "WEBSOCKETS_GET_INVITE_SUCCESS";
export const WEBSOCKETS_FRIEND_CHANGE_STATUS_SUCCESS =
  "WEBSOCKETS_FRIEND_CHANGE_STATUS_SUCCESS";
export const WEBSOCKETS_FIND_USER_BY_ID_SUCCESS =
  "WEBSOCKETS_FIND_USER_BY_ID_SUCCESS";
export const WEBSOCKETS_FIND_USER_BY_ID_FAIL =
  "WEBSOCKETS_FIND_USER_BY_ID_FAIL";
export const WEBSOCKETS_REFRESH_INVITATIONS_AND_MESSAGES_IDS_SUCCESS =
  "WEBSOCKETS_REFRESH_INVITATIONS_AND_MESSAGES_IDS_SUCCESS";
export const WEBSOCKETS_REFRESH_INVITATIONS_AND_MESSAGES_IDS_FAIL =
  "WEBSOCKETS_REFRESH_INVITATIONS_AND_MESSAGES_IDS_FAIL";
export const WEBSOCKETS_NOTIFICATIONS_LIST_SUCCESS =
  "WEBSOCKETS_NOTIFICATIONS_LIST_SUCCESS";
export const WEBSOCKETS_NOTIFICATIONS_LIST_FAIL =
  "WEBSOCKETS_NOTIFICATIONS_LIST_FAIL";
export const WEBSOCKETS_NOTIFICATIONS_LIST_NEXT_SUCCESS =
  "WEBSOCKETS_NOTIFICATIONS_LIST_NEXT_SUCCESS";
export const WEBSOCKETS_NOTIFICATIONS_LIST_NEXT_FAIL =
  "WEBSOCKETS_NOTIFICATIONS_LIST_NEXT_FAIL";
export const WEBSOCKETS_GET_NOTIFICATION_SUCCESS =
  "WEBSOCKETS_GET_NOTIFICATION_SUCCESS";
export const WEBSOCKETS_SEEN_NOTIFICATIONS_FAIL =
  "WEBSOCKETS_SEEN_NOTIFICATIONS_FAIL";
export const EVENT_TICKETS_SUCCESS = "EVENT_TICKETS_SUCCESS";
export const EVENT_TICKETS_NOTVALID_SUCCESS = "EVENT_TICKETS_NOTVALID_SUCCESS";
export const EVENT_TICKETS_FAIL = "EVENT_TICKETS_FAIL";
export const BANK_NUMBER_SUCCESS = "BANK_NUMBER_SUCCESS";
export const BANK_NUMBER_FAIL = "BANK_NUMBER_FAIL";
export const BANK_NUMBER_CHANGE_SUCCESS = "BANK_NUMBER_CHANGE_SUCCESS";
export const BANK_NUMBER_CHANGE_FAIL = "BANK_NUMBER_CHANGE_FAIL";
export const BANK_NUMBER_CHANGE_CONFIRM_SUCCESS =
  "BANK_NUMBER_CHANGE_CONFIRM_SUCCESS";
export const BANK_NUMBER_CHANGE_CONFIRM_NOTVALID_SUCCESS =
  "BANK_NUMBER_CHANGE_CONFIRM_NOTVALID_SUCCESS";
export const BANK_NUMBER_CHANGE_CONFIRM_FAIL =
  "BANK_NUMBER_CHANGE_CONFIRM_FAIL";
export const SET_PINNED_BANK = "SET_PINNED_BANK";
export const SET_UNPINNED_BANK = "SET_UNPINNED_BANK";
export const EVENT_VIA_TICKETS_SUCCESS = "EVENT_VIA_TICKETS_SUCCESS";
export const EVENT_VIA_TICKETS_FAIL = "EVENT_VIA_TICKETS_FAIL";
export const TICKET_CREATE_SUCCESS = "TICKET_CREATE_SUCCESS";
export const TICKET_CREATE_FAIL = "TICKET_CREATE_FAIL";
export const TICKET_CREATE_NOTVALID_SUCCESS = "TICKET_CREATE_NOTVALID_SUCCESS";
export const TICKET_EDIT_SUCCESS = "TICKET_EDIT_SUCCESS";
export const TICKET_EDIT_FAIL = "TICKET_EDIT_FAIL";
export const TICKET_EDIT_NOTVALID_SUCCESS = "TICKET_EDIT_NOTVALID_SUCCESS";
export const TICKET_DELETE_SUCCESS = "TICKET_DELETE_SUCCESS";
export const TICKET_DELETE_FAIL = "TICKET_DELETE_FAIL";
export const TICKET_DELETE_NOTVALID_SUCCESS = "TICKET_DELETE_NOTVALID_SUCCESS";
export const TICKET_PAY_SUCCESS = "TICKET_PAY_SUCCESS";
export const TICKET_PAY_FAIL = "TICKET_PAY_FAIL";
export const TICKET_PAY_NOTVALID_SUCCESS = "TICKET_PAY_NOTVALID_SUCCESS";
export const TICKET_GENERATE_PDF_SUCCESS = "TICKET_GENERATE_PDF_SUCCESS";
export const TICKET_GENERATE_PDF_FAIL = "TICKET_GENERATE_PDF_FAIL";
export const TICKET_GENERATE_PDF_NOTVALID_SUCCESS =
  "TICKET_GENERATE_PDF_NOTVALID_SUCCESS";
export const TICKET_REFUND_SUCCESS = "TICKET_REFUND_SUCCESS";
export const TICKET_REFUND_FAIL = "TICKET_REFUND_FAIL";
export const TICKET_REFUND_NOTVALID_SUCCESS = "TICKET_REFUND_NOTVALID_SUCCESS";
export const TICKET_ORDER_CANCEL_SUCCESS = "TICKET_ORDER_CANCEL_SUCCESS";
export const TICKET_ORDER_REPAY_SUCCESS = "TICKET_ORDER_REPAY_SUCCESS";
export const TICKET_ORDER_ACTION_FAIL = "TICKET_ORDER_ACTION_FAIL";
export const TICKET_ORDER_ACTION_NOTVALID_SUCCESS =
  "TICKET_ORDER_ACTION_NOTVALID_SUCCESS";
export const TICKET_CALENDAR_SUCCESS = "TICKET_CALENDAR_SUCCESS";
export const TICKET_CALENDAR_FAIL = "TICKET_CALENDAR_FAIL";
export const WEBSOCKETS_TICKET_CHANGE_STATUS_SUCCESS =
  "WEBSOCKETS_TICKET_CHANGE_STATUS_SUCCESS";
export const WEBSOCKETS_ORDER_REFUND_SUCCESS =
  "WEBSOCKETS_ORDER_REFUND_SUCCESS";
export const ADMIN_OPEN_GATEWAY_PAYCHECK_SUCCESS =
  "ADMIN_OPEN_GATEWAY_PAYCHECK_SUCCESS";
export const ADMIN_OPEN_GATEWAY_PAYCHECK_ALREADY_OPENED_SUCCESS =
  "ADMIN_OPEN_GATEWAY_PAYCHECK_ALREADY_OPENED_SUCCESS";
export const ADMIN_OPEN_GATEWAY_PAYCHECK_FAIL =
  "ADMIN_OPEN_GATEWAY_PAYCHECK_FAIL";
export const WEBSOCKETS_PAYCHECK_RECEIVE_SUCCESS =
  "WEBSOCKETS_PAYCHECK_RECEIVE_SUCCESS";
export const PAYMENT_CONFIRMATION_PDF_SUCCESS =
  "PAYMENT_CONFIRMATION_PDF_SUCCESS";
export const PAYMENT_CONFIRMATION_PDF_FAIL = "PAYMENT_CONFIRMATION_PDF_FAIL";
export const WEBSOCKETS_REFUND_NOT_PINNED_BANK_SUCCESS =
  "WEBSOCKETS_REFUND_NOT_PINNED_BANK_SUCCESS";
